/*
 * Auto-generated test file
 * Generated by gen_c_tests_v2.py from test_definitions.py
 * Total test cases: 100
 */

#include <unity.h>
#include <rbc/glob.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Helper function to compare glob results with Ruby expected output */
static void test_glob_against_ruby(const char *pattern, int flags, 
                                   const char *base, bool sort,
                                   const char *expected_file)
{
    rbc_str_list_t result = {0};
    
    /* Execute rbc_glob */
    int ret = rbc_glob(pattern, flags, NULL, &result);
    TEST_ASSERT_EQUAL_INT(0, ret);
    
    /* Load expected results from Ruby */
    FILE *fp = fopen(expected_file, "r");
    TEST_ASSERT_NOT_NULL_MESSAGE(fp, "Failed to open expected file");
    
    char **expected_lines = NULL;
    size_t expected_count = 0;
    size_t capacity = 16;
    expected_lines = malloc(capacity * sizeof(char*));
    TEST_ASSERT_NOT_NULL(expected_lines);
    
    char line[4096];
    while (fgets(line, sizeof(line), fp)) {
        /* Remove trailing newline */
        size_t len = strlen(line);
        if (len > 0 && line[len-1] == '\n') {
            line[len-1] = '\0';
        }
        
        if (expected_count >= capacity) {
            capacity *= 2;
            expected_lines = realloc(expected_lines, capacity * sizeof(char*));
            TEST_ASSERT_NOT_NULL(expected_lines);
        }
        
        expected_lines[expected_count++] = strdup(line);
    }
    fclose(fp);
    
    /* Compare counts */
    char count_msg[256];
    snprintf(count_msg, sizeof(count_msg), 
             "Pattern: %s, Expected: %zu, Got: %zu",
             pattern, expected_count, result.count);
    TEST_ASSERT_EQUAL_size_t_MESSAGE(expected_count, result.count, count_msg);
    
    /* Compare each result */
    for (size_t i = 0; i < expected_count; i++) {
        char msg[512];
        snprintf(msg, sizeof(msg), 
                 "Pattern: %s, Index: %zu, Expected: %s, Got: %s",
                 pattern, i, expected_lines[i], 
                 i < result.count ? result.strings[i] : "NULL");
        TEST_ASSERT_EQUAL_STRING_MESSAGE(expected_lines[i], result.strings[i], msg);
    }
    
    /* Cleanup */
    for (size_t i = 0; i < expected_count; i++) {
        free(expected_lines[i]);
    }
    free(expected_lines);
    rbc_str_list_free(&result);
}

void setUp(void) {
    /* Set up code (if needed) */
}

void tearDown(void) {
    /* Tear down code (if needed) */
}


/* ========== Test Functions ========== */

void test_t1000(void)
{
    /* Matrix: 01_basic/file */
    const char *pattern = "01_basic/file";
    int flags = 0;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1000.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1001(void)
{
    /* Matrix: 01_basic/file, unsorted */
    const char *pattern = "01_basic/file";
    int flags = 0;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1001.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1002(void)
{
    /* Matrix: 01_basic/file, base=. */
    const char *pattern = "01_basic/file";
    int flags = 0;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1002.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1003(void)
{
    /* Matrix: 01_basic/file, flags=DOTMATCH */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1003.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1004(void)
{
    /* Matrix: 01_basic/file, flags=DOTMATCH, unsorted */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1004.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1005(void)
{
    /* Matrix: 01_basic/file, flags=DOTMATCH, base=. */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_DOTMATCH;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1005.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1006(void)
{
    /* Matrix: 01_basic/file, flags=PATHNAME */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_PATHNAME;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1006.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1007(void)
{
    /* Matrix: 01_basic/file, flags=PATHNAME, unsorted */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_PATHNAME;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1007.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1008(void)
{
    /* Matrix: 01_basic/file, flags=PATHNAME, base=. */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_PATHNAME;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1008.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1009(void)
{
    /* Matrix: 01_basic/file, flags=CASEFOLD */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1009.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1010(void)
{
    /* Matrix: 01_basic/file, flags=CASEFOLD, unsorted */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1010.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1011(void)
{
    /* Matrix: 01_basic/file, flags=CASEFOLD, base=. */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_CASEFOLD;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1011.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1012(void)
{
    /* Matrix: 01_basic/file, flags=PATHNAME|DOTMATCH */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1012.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1013(void)
{
    /* Matrix: 01_basic/file, flags=PATHNAME|DOTMATCH, unsorted */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1013.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1014(void)
{
    /* Matrix: 01_basic/file, flags=PATHNAME|DOTMATCH, base=. */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_DOTMATCH;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1014.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1015(void)
{
    /* Matrix: 01_basic/file, flags=PATHNAME|CASEFOLD */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1015.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1016(void)
{
    /* Matrix: 01_basic/file, flags=PATHNAME|CASEFOLD, unsorted */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1016.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1017(void)
{
    /* Matrix: 01_basic/file, flags=PATHNAME|CASEFOLD, base=. */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_CASEFOLD;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1017.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1018(void)
{
    /* Matrix: 01_basic/file, flags=DOTMATCH|CASEFOLD */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_DOTMATCH | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1018.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1019(void)
{
    /* Matrix: 01_basic/file, flags=DOTMATCH|CASEFOLD, unsorted */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_DOTMATCH | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1019.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1020(void)
{
    /* Matrix: 01_basic/file, flags=DOTMATCH|CASEFOLD, base=. */
    const char *pattern = "01_basic/file";
    int flags = RBC_FNM_DOTMATCH | RBC_FNM_CASEFOLD;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1020.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1021(void)
{
    /* Matrix: 01_basic/file.txt */
    const char *pattern = "01_basic/file.txt";
    int flags = 0;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1021.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1022(void)
{
    /* Matrix: 01_basic/file.txt, unsorted */
    const char *pattern = "01_basic/file.txt";
    int flags = 0;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1022.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1023(void)
{
    /* Matrix: 01_basic/file.txt, base=src */
    const char *pattern = "01_basic/file.txt";
    int flags = 0;
    const char *base = "src";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1023.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1024(void)
{
    /* Matrix: 01_basic/file.txt, base=tests */
    const char *pattern = "01_basic/file.txt";
    int flags = 0;
    const char *base = "tests";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1024.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1025(void)
{
    /* Matrix: 01_basic/file.txt, base=. */
    const char *pattern = "01_basic/file.txt";
    int flags = 0;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1025.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1026(void)
{
    /* Matrix: 01_basic/file.txt, flags=DOTMATCH */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1026.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1027(void)
{
    /* Matrix: 01_basic/file.txt, flags=DOTMATCH, unsorted */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1027.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1028(void)
{
    /* Matrix: 01_basic/file.txt, flags=DOTMATCH, base=src */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_DOTMATCH;
    const char *base = "src";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1028.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1029(void)
{
    /* Matrix: 01_basic/file.txt, flags=DOTMATCH, base=tests */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_DOTMATCH;
    const char *base = "tests";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1029.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1030(void)
{
    /* Matrix: 01_basic/file.txt, flags=DOTMATCH, base=. */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_DOTMATCH;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1030.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1031(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1031.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1032(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME, unsorted */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1032.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1033(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME, base=src */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME;
    const char *base = "src";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1033.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1034(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME, base=tests */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME;
    const char *base = "tests";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1034.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1035(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME, base=. */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1035.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1036(void)
{
    /* Matrix: 01_basic/file.txt, flags=CASEFOLD */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1036.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1037(void)
{
    /* Matrix: 01_basic/file.txt, flags=CASEFOLD, unsorted */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1037.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1038(void)
{
    /* Matrix: 01_basic/file.txt, flags=CASEFOLD, base=src */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_CASEFOLD;
    const char *base = "src";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1038.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1039(void)
{
    /* Matrix: 01_basic/file.txt, flags=CASEFOLD, base=tests */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_CASEFOLD;
    const char *base = "tests";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1039.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1040(void)
{
    /* Matrix: 01_basic/file.txt, flags=CASEFOLD, base=. */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_CASEFOLD;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1040.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1041(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME|DOTMATCH */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1041.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1042(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME|DOTMATCH, unsorted */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1042.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1043(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME|DOTMATCH, base=src */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_DOTMATCH;
    const char *base = "src";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1043.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1044(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME|DOTMATCH, base=tests */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_DOTMATCH;
    const char *base = "tests";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1044.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1045(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME|DOTMATCH, base=. */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_DOTMATCH;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1045.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1046(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME|CASEFOLD */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1046.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1047(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME|CASEFOLD, unsorted */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1047.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1048(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME|CASEFOLD, base=src */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_CASEFOLD;
    const char *base = "src";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1048.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1049(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME|CASEFOLD, base=tests */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_CASEFOLD;
    const char *base = "tests";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1049.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1050(void)
{
    /* Matrix: 01_basic/file.txt, flags=PATHNAME|CASEFOLD, base=. */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_CASEFOLD;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1050.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1051(void)
{
    /* Matrix: 01_basic/file.txt, flags=DOTMATCH|CASEFOLD */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_DOTMATCH | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1051.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1052(void)
{
    /* Matrix: 01_basic/file.txt, flags=DOTMATCH|CASEFOLD, unsorted */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_DOTMATCH | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1052.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1053(void)
{
    /* Matrix: 01_basic/file.txt, flags=DOTMATCH|CASEFOLD, base=src */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_DOTMATCH | RBC_FNM_CASEFOLD;
    const char *base = "src";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1053.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1054(void)
{
    /* Matrix: 01_basic/file.txt, flags=DOTMATCH|CASEFOLD, base=tests */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_DOTMATCH | RBC_FNM_CASEFOLD;
    const char *base = "tests";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1054.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1055(void)
{
    /* Matrix: 01_basic/file.txt, flags=DOTMATCH|CASEFOLD, base=. */
    const char *pattern = "01_basic/file.txt";
    int flags = RBC_FNM_DOTMATCH | RBC_FNM_CASEFOLD;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1055.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1056(void)
{
    /* Matrix: 01_basic/dir */
    const char *pattern = "01_basic/dir";
    int flags = 0;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1056.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1057(void)
{
    /* Matrix: 01_basic/dir, unsorted */
    const char *pattern = "01_basic/dir";
    int flags = 0;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1057.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1058(void)
{
    /* Matrix: 01_basic/dir, base=. */
    const char *pattern = "01_basic/dir";
    int flags = 0;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1058.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1059(void)
{
    /* Matrix: 01_basic/dir, flags=DOTMATCH */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1059.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1060(void)
{
    /* Matrix: 01_basic/dir, flags=DOTMATCH, unsorted */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1060.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1061(void)
{
    /* Matrix: 01_basic/dir, flags=DOTMATCH, base=. */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_DOTMATCH;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1061.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1062(void)
{
    /* Matrix: 01_basic/dir, flags=PATHNAME */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_PATHNAME;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1062.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1063(void)
{
    /* Matrix: 01_basic/dir, flags=PATHNAME, unsorted */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_PATHNAME;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1063.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1064(void)
{
    /* Matrix: 01_basic/dir, flags=PATHNAME, base=. */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_PATHNAME;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1064.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1065(void)
{
    /* Matrix: 01_basic/dir, flags=CASEFOLD */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1065.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1066(void)
{
    /* Matrix: 01_basic/dir, flags=CASEFOLD, unsorted */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1066.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1067(void)
{
    /* Matrix: 01_basic/dir, flags=CASEFOLD, base=. */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_CASEFOLD;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1067.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1068(void)
{
    /* Matrix: 01_basic/dir, flags=PATHNAME|DOTMATCH */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1068.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1069(void)
{
    /* Matrix: 01_basic/dir, flags=PATHNAME|DOTMATCH, unsorted */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1069.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1070(void)
{
    /* Matrix: 01_basic/dir, flags=PATHNAME|DOTMATCH, base=. */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_DOTMATCH;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1070.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1071(void)
{
    /* Matrix: 01_basic/dir, flags=PATHNAME|CASEFOLD */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1071.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1072(void)
{
    /* Matrix: 01_basic/dir, flags=PATHNAME|CASEFOLD, unsorted */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1072.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1073(void)
{
    /* Matrix: 01_basic/dir, flags=PATHNAME|CASEFOLD, base=. */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_CASEFOLD;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1073.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1074(void)
{
    /* Matrix: 01_basic/dir, flags=DOTMATCH|CASEFOLD */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_DOTMATCH | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1074.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1075(void)
{
    /* Matrix: 01_basic/dir, flags=DOTMATCH|CASEFOLD, unsorted */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_DOTMATCH | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1075.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1076(void)
{
    /* Matrix: 01_basic/dir, flags=DOTMATCH|CASEFOLD, base=. */
    const char *pattern = "01_basic/dir";
    int flags = RBC_FNM_DOTMATCH | RBC_FNM_CASEFOLD;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1076.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1077(void)
{
    /* Matrix: 01_basic/dir/ */
    const char *pattern = "01_basic/dir/";
    int flags = 0;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1077.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1078(void)
{
    /* Matrix: 01_basic/dir/, unsorted */
    const char *pattern = "01_basic/dir/";
    int flags = 0;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1078.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1079(void)
{
    /* Matrix: 01_basic/dir/, base=. */
    const char *pattern = "01_basic/dir/";
    int flags = 0;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1079.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1080(void)
{
    /* Matrix: 01_basic/dir/, flags=DOTMATCH */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1080.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1081(void)
{
    /* Matrix: 01_basic/dir/, flags=DOTMATCH, unsorted */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1081.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1082(void)
{
    /* Matrix: 01_basic/dir/, flags=DOTMATCH, base=. */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_DOTMATCH;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1082.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1083(void)
{
    /* Matrix: 01_basic/dir/, flags=PATHNAME */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_PATHNAME;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1083.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1084(void)
{
    /* Matrix: 01_basic/dir/, flags=PATHNAME, unsorted */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_PATHNAME;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1084.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1085(void)
{
    /* Matrix: 01_basic/dir/, flags=PATHNAME, base=. */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_PATHNAME;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1085.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1086(void)
{
    /* Matrix: 01_basic/dir/, flags=CASEFOLD */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1086.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1087(void)
{
    /* Matrix: 01_basic/dir/, flags=CASEFOLD, unsorted */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1087.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1088(void)
{
    /* Matrix: 01_basic/dir/, flags=CASEFOLD, base=. */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_CASEFOLD;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1088.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1089(void)
{
    /* Matrix: 01_basic/dir/, flags=PATHNAME|DOTMATCH */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1089.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1090(void)
{
    /* Matrix: 01_basic/dir/, flags=PATHNAME|DOTMATCH, unsorted */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_DOTMATCH;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1090.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1091(void)
{
    /* Matrix: 01_basic/dir/, flags=PATHNAME|DOTMATCH, base=. */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_DOTMATCH;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1091.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1092(void)
{
    /* Matrix: 01_basic/dir/, flags=PATHNAME|CASEFOLD */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1092.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1093(void)
{
    /* Matrix: 01_basic/dir/, flags=PATHNAME|CASEFOLD, unsorted */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1093.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1094(void)
{
    /* Matrix: 01_basic/dir/, flags=PATHNAME|CASEFOLD, base=. */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_PATHNAME | RBC_FNM_CASEFOLD;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1094.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1095(void)
{
    /* Matrix: 01_basic/dir/, flags=DOTMATCH|CASEFOLD */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_DOTMATCH | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1095.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1096(void)
{
    /* Matrix: 01_basic/dir/, flags=DOTMATCH|CASEFOLD, unsorted */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_DOTMATCH | RBC_FNM_CASEFOLD;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1096.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1097(void)
{
    /* Matrix: 01_basic/dir/, flags=DOTMATCH|CASEFOLD, base=. */
    const char *pattern = "01_basic/dir/";
    int flags = RBC_FNM_DOTMATCH | RBC_FNM_CASEFOLD;
    const char *base = ".";
    bool sort = true;
    const char *expected_file = "ruby_expected/t1097.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1098(void)
{
    /* Matrix: 02_asterisk/* */
    const char *pattern = "02_asterisk/*";
    int flags = 0;
    const char *base = NULL;
    bool sort = true;
    const char *expected_file = "ruby_expected/t1098.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


void test_t1099(void)
{
    /* Matrix: 02_asterisk/*, unsorted */
    const char *pattern = "02_asterisk/*";
    int flags = 0;
    const char *base = NULL;
    bool sort = false;
    const char *expected_file = "ruby_expected/t1099.txt";
    
    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}


/* ========== Main Function ========== */

int main(void)
{
    UNITY_BEGIN();
    
    RUN_TEST(test_t1000);
    RUN_TEST(test_t1001);
    RUN_TEST(test_t1002);
    RUN_TEST(test_t1003);
    RUN_TEST(test_t1004);
    RUN_TEST(test_t1005);
    RUN_TEST(test_t1006);
    RUN_TEST(test_t1007);
    RUN_TEST(test_t1008);
    RUN_TEST(test_t1009);
    RUN_TEST(test_t1010);
    RUN_TEST(test_t1011);
    RUN_TEST(test_t1012);
    RUN_TEST(test_t1013);
    RUN_TEST(test_t1014);
    RUN_TEST(test_t1015);
    RUN_TEST(test_t1016);
    RUN_TEST(test_t1017);
    RUN_TEST(test_t1018);
    RUN_TEST(test_t1019);
    RUN_TEST(test_t1020);
    RUN_TEST(test_t1021);
    RUN_TEST(test_t1022);
    RUN_TEST(test_t1023);
    RUN_TEST(test_t1024);
    RUN_TEST(test_t1025);
    RUN_TEST(test_t1026);
    RUN_TEST(test_t1027);
    RUN_TEST(test_t1028);
    RUN_TEST(test_t1029);
    RUN_TEST(test_t1030);
    RUN_TEST(test_t1031);
    RUN_TEST(test_t1032);
    RUN_TEST(test_t1033);
    RUN_TEST(test_t1034);
    RUN_TEST(test_t1035);
    RUN_TEST(test_t1036);
    RUN_TEST(test_t1037);
    RUN_TEST(test_t1038);
    RUN_TEST(test_t1039);
    RUN_TEST(test_t1040);
    RUN_TEST(test_t1041);
    RUN_TEST(test_t1042);
    RUN_TEST(test_t1043);
    RUN_TEST(test_t1044);
    RUN_TEST(test_t1045);
    RUN_TEST(test_t1046);
    RUN_TEST(test_t1047);
    RUN_TEST(test_t1048);
    RUN_TEST(test_t1049);
    RUN_TEST(test_t1050);
    RUN_TEST(test_t1051);
    RUN_TEST(test_t1052);
    RUN_TEST(test_t1053);
    RUN_TEST(test_t1054);
    RUN_TEST(test_t1055);
    RUN_TEST(test_t1056);
    RUN_TEST(test_t1057);
    RUN_TEST(test_t1058);
    RUN_TEST(test_t1059);
    RUN_TEST(test_t1060);
    RUN_TEST(test_t1061);
    RUN_TEST(test_t1062);
    RUN_TEST(test_t1063);
    RUN_TEST(test_t1064);
    RUN_TEST(test_t1065);
    RUN_TEST(test_t1066);
    RUN_TEST(test_t1067);
    RUN_TEST(test_t1068);
    RUN_TEST(test_t1069);
    RUN_TEST(test_t1070);
    RUN_TEST(test_t1071);
    RUN_TEST(test_t1072);
    RUN_TEST(test_t1073);
    RUN_TEST(test_t1074);
    RUN_TEST(test_t1075);
    RUN_TEST(test_t1076);
    RUN_TEST(test_t1077);
    RUN_TEST(test_t1078);
    RUN_TEST(test_t1079);
    RUN_TEST(test_t1080);
    RUN_TEST(test_t1081);
    RUN_TEST(test_t1082);
    RUN_TEST(test_t1083);
    RUN_TEST(test_t1084);
    RUN_TEST(test_t1085);
    RUN_TEST(test_t1086);
    RUN_TEST(test_t1087);
    RUN_TEST(test_t1088);
    RUN_TEST(test_t1089);
    RUN_TEST(test_t1090);
    RUN_TEST(test_t1091);
    RUN_TEST(test_t1092);
    RUN_TEST(test_t1093);
    RUN_TEST(test_t1094);
    RUN_TEST(test_t1095);
    RUN_TEST(test_t1096);
    RUN_TEST(test_t1097);
    RUN_TEST(test_t1098);
    RUN_TEST(test_t1099);
    
    return UNITY_END();
}
