#!/usr/bin/env python3
"""
Unityテストコード生成スクリプト (File.fnmatch版)

test_definitions.pyからfnmatchテストケースを読み込み、
Unity形式のCテストコードを生成する。
"""

import sys
from pathlib import Path
from test_definitions import get_fnmatch_test_cases, FNMFlags


def flags_to_c(flags: FNMFlags) -> str:
    """FNMFlagsをC言語の定数表現に変換"""
    if flags == FNMFlags.NONE:
        return "0"

    flag_parts = []
    if flags & FNMFlags.NOESCAPE:
        flag_parts.append("RBC_FNM_NOESCAPE")
    if flags & FNMFlags.PATHNAME:
        flag_parts.append("RBC_FNM_PATHNAME")
    if flags & FNMFlags.DOTMATCH:
        flag_parts.append("RBC_FNM_DOTMATCH")
    if flags & FNMFlags.CASEFOLD:
        flag_parts.append("RBC_FNM_CASEFOLD")
    if flags & FNMFlags.EXTGLOB:
        flag_parts.append("RBC_FNM_EXTGLOB")

    return " | ".join(flag_parts) if flag_parts else "0"


def escape_c_string(s):
    """C言語文字列リテラル用にエスケープ"""
    s = s.replace('\\', '\\\\')  # \ -> \\
    s = s.replace('"', '\\"')    # " -> \"
    s = s.replace('\n', '\\n')   # 改行 -> \n
    s = s.replace('\t', '\\t')   # タブ -> \t
    s = s.replace('\r', '\\r')   # CR -> \r
    return s


def generate_test_function(test_case):
    """テストケースからUnityテスト関数を生成"""
    case_id = test_case.id
    pattern = escape_c_string(test_case.pattern)
    text = escape_c_string(test_case.text)
    flags = flags_to_c(test_case.flags)

    # コメント用の説明（*/を含まないようにサニタイズ）
    desc = test_case.desc if test_case.desc else f"Pattern: '{pattern}', Text: '{text}'"
    desc = desc.replace('*/', '* /')  # コメント終了を回避

    code = f'''
void test_{case_id}(void)
{{
    /* {desc} */
    const char *pattern = "{pattern}";
    const char *text = "{text}";
    unsigned flags = {flags};
    const char *expected_file = "tests/ruby_fnmatch_expected/{case_id}.txt";

    /* Load Ruby expected result */
    FILE *fp = fopen(expected_file, "r");
    TEST_ASSERT_NOT_NULL_MESSAGE(fp, "Failed to open expected file");

    char expected_str[16];
    TEST_ASSERT_NOT_NULL(fgets(expected_str, sizeof(expected_str), fp));
    fclose(fp);

    /* Remove trailing newline */
    size_t len = strlen(expected_str);
    if (len > 0 && expected_str[len - 1] == '\\n') {{
        expected_str[len - 1] = '\\0';
    }}

    bool expected = (strcmp(expected_str, "true") == 0);

    /* Execute rbc_fnmatch */
    bool result = rbc_fnmatch(pattern, text, flags);

    /* Compare with Ruby result */
    TEST_ASSERT_EQUAL_MESSAGE(expected, result, "Result mismatch with Ruby File.fnmatch");
}}
'''

    return code


def generate_test_file(test_cases, output_file):
    """全テストケースからCファイルを生成"""

    # ヘッダー
    header = f'''/*
 * Auto-generated test file for File.fnmatch compatibility
 * Generated by gen_c_fnmatch_tests.py from test_definitions.py
 * Total test cases: {len(test_cases)}
 */

#include <unity.h>
#include <rbc/rbc.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void setUp(void) {{
    /* Set up before each test */
}}

void tearDown(void) {{
    /* Clean up after each test */
}}

/* ========================================================================
 * Test Functions
 * ======================================================================== */
'''

    # テスト関数生成
    test_functions = []
    for test_case in test_cases:
        test_functions.append(generate_test_function(test_case))

    # Unity runner用のリスト生成
    runner_header = f'''

/* ========================================================================
 * Unity Runner
 * ======================================================================== */

int main(void)
{{
    UNITY_BEGIN();

'''

    # RUN_TEST呼び出し
    run_test_calls = []
    for test_case in test_cases:
        run_test_calls.append(f"    RUN_TEST(test_{test_case.id});")

    runner_footer = '''
    return UNITY_END();
}
'''

    # ファイル結合
    content = (
        header +
        "\n".join(test_functions) +
        runner_header +
        "\n".join(run_test_calls) +
        runner_footer
    )

    # ファイル書き込み
    output_file.write_text(content)

    return len(test_cases)


def main():
    """メイン処理"""
    print("=" * 60)
    print("🔨 Generating C Test Code (File.fnmatch)")
    print("=" * 60)

    # 出力ディレクトリ作成
    script_dir = Path(__file__).parent
    tests_dir = script_dir.parent
    output_dir = tests_dir / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "test_fnmatch_ruby_compat.c"

    print(f"📂 Output directory: {output_dir}")
    print(f"📄 Output file: {output_file}")

    # テストケース取得
    test_cases = get_fnmatch_test_cases()
    print(f"📋 Total test cases: {len(test_cases)}\n")

    # C言語テストファイル生成
    print("  Generating test functions...")
    count = generate_test_file(test_cases, output_file)

    print("\n" + "=" * 60)
    print("📊 Summary")
    print("=" * 60)
    print(f"  ✅ Generated: {count} test functions")
    print(f"  📄 Output: {output_file}")
    print(f"  📏 File size: {output_file.stat().st_size:,} bytes")
    print("=" * 60)

    return 0


if __name__ == "__main__":
    sys.exit(main())
