#!/usr/bin/env python3
"""
Unityテストコード生成スクリプト v2

test_definitions.pyから直接テストケースを読み込み、
Unity形式のCテストコードを生成する。
"""

import sys
from pathlib import Path
from test_definitions import get_all_test_cases, FIXTURES_DIR, FNMFlags


def flags_to_c(flags: FNMFlags) -> str:
    """FNMFlagsをC言語の定数表現に変換"""
    if flags == FNMFlags.NONE:
        return "0"

    flag_parts = []
    if flags & FNMFlags.NOESCAPE:
        flag_parts.append("RBC_FNM_NOESCAPE")
    if flags & FNMFlags.PATHNAME:
        flag_parts.append("RBC_FNM_PATHNAME")
    if flags & FNMFlags.DOTMATCH:
        flag_parts.append("RBC_FNM_DOTMATCH")
    if flags & FNMFlags.CASEFOLD:
        flag_parts.append("RBC_FNM_CASEFOLD")
    if flags & FNMFlags.EXTGLOB:
        flag_parts.append("RBC_FNM_EXTGLOB")

    return " | ".join(flag_parts) if flag_parts else "0"


def escape_c_string(s):
    """C言語文字列リテラル用にエスケープ"""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')


def generate_test_function(test_case, test_num):
    """テストケースからUnityテスト関数を生成"""
    case_id = test_case.id
    pattern = escape_c_string(test_case.pattern)
    flags = flags_to_c(test_case.flags)
    base = test_case.base
    sort = "true" if test_case.sort else "false"

    # baseパラメータ
    if base is None:
        base_arg = "NULL"
    else:
        base_arg = f'"{escape_c_string(base)}"'

    # コメント用の説明（*/を含まないようにサニタイズ）
    desc = test_case.desc if test_case.desc else f"Pattern: {pattern}"
    desc = desc.replace('*/', '* /')  # コメント終了を回避

    code = f'''
void test_{case_id}(void)
{{
    /* {desc} */
    const char *pattern = "{pattern}";
    int flags = {flags};
    const char *base = {base_arg};
    bool sort = {sort};
    const char *expected_file = "../ruby_expected/{case_id}.txt";

    test_glob_against_ruby(pattern, flags, base, sort, expected_file);
}}
'''

    return code


def generate_test_file(test_cases, output_file):
    """全テストケースからCファイルを生成"""

    # ヘッダー
    header = f'''/*
 * Auto-generated test file
 * Generated by gen_c_tests.py from test_definitions.py
 * Total test cases: {len(test_cases)}
 */

#include <unity.h>
#include <rbc/rbc.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Helper function to compare glob results with Ruby expected output */
static void test_glob_against_ruby(const char *pattern, int flags,
                                   const char *base, bool sort,
                                   const char *expected_file)
{{
    char **results = NULL;
    size_t count = 0;
    size_t *lengths = NULL;

    /* Execute rbc_glob */
    const char *patterns[] = {{pattern}};
    bool ret = rbc_glob(patterns, 1, flags, base, sort, &results, &count, &lengths);
    TEST_ASSERT_TRUE_MESSAGE(ret, "rbc_glob failed");

    /* Load expected results from Ruby */
    FILE *fp = fopen(expected_file, "r");
    TEST_ASSERT_NOT_NULL_MESSAGE(fp, "Failed to open expected file");

    char **expected_lines = NULL;
    size_t expected_count = 0;
    size_t capacity = 16;
    expected_lines = malloc(capacity * sizeof(char*));
    TEST_ASSERT_NOT_NULL(expected_lines);

    char line[4096];
    while (fgets(line, sizeof(line), fp)) {{
        /* Remove trailing newline */
        size_t len = strlen(line);
        if (len > 0 && line[len-1] == '\\n') {{
            line[len-1] = '\\0';
        }}

        if (expected_count >= capacity) {{
            capacity *= 2;
            expected_lines = realloc(expected_lines, capacity * sizeof(char*));
            TEST_ASSERT_NOT_NULL(expected_lines);
        }}

        expected_lines[expected_count++] = strdup(line);
    }}
    fclose(fp);

    /* Compare counts */
    char count_msg[256];
    snprintf(count_msg, sizeof(count_msg),
             "Pattern: %s, Expected: %zu, Got: %zu",
             pattern, expected_count, count);
    TEST_ASSERT_EQUAL_size_t_MESSAGE(expected_count, count, count_msg);

    /* Compare each result */
    for (size_t i = 0; i < expected_count; i++) {{
        char msg[512];
        snprintf(msg, sizeof(msg),
                 "Pattern: %s, Index: %zu, Expected: %s, Got: %s",
                 pattern, i, expected_lines[i],
                 i < count ? results[i] : "NULL");
        TEST_ASSERT_EQUAL_STRING_MESSAGE(expected_lines[i], results[i], msg);
    }}

    /* Cleanup */
    for (size_t i = 0; i < expected_count; i++) {{
        free(expected_lines[i]);
    }}
    free(expected_lines);
    rbc_glob_free(results, count, lengths);
}}

void setUp(void) {{
    /* Set up code (if needed) */
}}

void tearDown(void) {{
    /* Tear down code (if needed) */
}}
'''

    # テスト関数生成
    test_functions = []
    for i, test_case in enumerate(test_cases, 1):
        test_functions.append(generate_test_function(test_case, i))

    # main関数
    test_calls = "\n    ".join(f"RUN_TEST(test_{tc.id});" for tc in test_cases)

    main_func = f'''
int main(void)
{{
    UNITY_BEGIN();

    {test_calls}

    return UNITY_END();
}}
'''

    # ファイル書き込み
    with open(output_file, 'w') as f:
        f.write(header)
        f.write("\n\n/* ========== Test Functions ========== */\n")
        f.write("\n".join(test_functions))
        f.write("\n\n/* ========== Main Function ========== */\n")
        f.write(main_func)


def main():
    """メイン処理"""
    print("=" * 60)
    print("🔨 Generating Unity Test Code")
    print("=" * 60)

    # 出力ファイル
    output_file = Path(__file__).parent.parent / "test_glob_generated.c"

    print(f"📂 Output file: {output_file}")

    # テストケース取得
    test_cases = get_all_test_cases()
    print(f"📋 Total test cases: {len(test_cases)}")

    # C言語テストファイル生成
    print("  Generating C test code...")
    generate_test_file(test_cases, output_file)

    print("\n" + "=" * 60)
    print("✅ Test code generated successfully")
    print("=" * 60)
    print(f"  📁 Output: {output_file}")
    print(f"  📝 Functions: {len(test_cases)}")
    print("=" * 60)

    return 0


if __name__ == "__main__":
    sys.exit(main())
